name: My First Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello"

      - name: print Date
        run: date

      - name: Print "Completed"
        run : echo "Completed"

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Runs action-a"
        uses: ./action-a 
        with:
          MY_NAME: "Tharin"

      - name: "Run All"
        run: |
          echo "Step 1 done"
          echo "Step 2 done"
          echo "All Done"

